import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

// Import your Navbar component
import Navbar from "./comps/Navbar" // or wherever your Navbar file is located

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Include the Navbar as part of the layout */}
        <Navbar />
        
        {/* Main content area */}
        {children}
      </body>
    </html>
  )
}
